### ISSUE TITLE
Undefined index in plugin.modescript_handler

### ISSUE THREAD

**Issue by Obiwan1995** [undeflabs/UASECO#49] opened 2019-05-24 18:44 UTC
When a player connects, at the end of the map and when updating server ranks for players, there are some errors in `plugin.modescript_handler.php`

```
[PHP Notice] Undefined index: prevracetime on line 912 in file uaseco/plugins/plugin.modescript_handler.php
[PHP Notice] Undefined index: prevracerespawns on line 913 in file uaseco/plugins/plugin.modescript_handler.php
[PHP Notice] Undefined index: prevracecheckpoints on line 914 in file uaseco/plugins/plugin.modescript_handler.php
[PHP Notice] Undefined index: prevstuntsscore on line 916 in file uaseco/plugins/plugin.modescript_handler.php
```

**Comment by undeflabs** [comment] 2019-05-25 08:37
It seems you are using and old or mixed versions UASECO installation or a old uaseco.php, because "prevrace*" where added in 0.9.6, or an old dedicated server version (in this case the uaseco.php was edited).

Please add the version of your dedicated server and UASECO also plugin.modescript_handler.php.

**Comment by Obiwan1995** [comment] 2019-05-26 18:28
I updated my dedicated server, but the error is still here.

Versions:
* `UASECO:        Version 0.9.6 build 2019-03-02`
* `plugin.modescript_handler.php                     1.0.5 build 2018-11-22`
*  `Dedicated:     ManiaPlanet/3.3.0 build 2019-05-23_18_00, using Method-API 2013-04-16, ModeScript-API 2.5.0`

**Comment by undeflabs** [comment] 2019-05-27 08:11
The 'prevracetime', 'prevracerespawns', 'prevracecheckpoints' and 'prevstuntsscore' are from the modescript. Which gamemode do you run and which version?

That looks like in the UASECO logfile:
`Gamemode: "TimeAttack" with script "TimeAttack.Script.txt" version "2018-05-14"`

And please make sure you are use one of the supported versions:
https://www.uaseco.org/documentation/supported-modescripts.php

**Comment by Obiwan1995** [comment] 2019-05-27 08:50
`Gamemode:      "TimeAttack" with script "TimeAttack.Script.txt" version "2018-05-14"`

Unfortunately, I use a supported version :/

**Comment by undeflabs** [comment] 2019-05-27 12:29
Well... that's strange. Please send me a PM at https://forum.maniaplanet.com/ucp.php?i=pm&mode=compose&u=1954 with your full UASECO logfile.

Maybe it's a good idea to send me also a download of your UASECO and dedicated server installation for further investigations. You should remove/replace the passwords first.

**Comment by undeflabs** [comment] 2019-06-05 18:19
After testing his installation on my system without any problems, I thing I could close this. Feel free to reopen if the problem is still existend.

**Closed by undeflabs** 2019-06-05 18:19 UTC
