### ISSUE TITLE
master branch destroys rasp/database !

### ISSUE THREAD

**Issue by BestNoob** [undeflabs/UASECO#37] opened 2018-12-06 13:15 UTC
after trying master branch 
/admin add MXID 
shows only unknown, maps wont get listed correctly.

Using my BACKUP wont fix the problems, seems MYSQL DATABSE is damaged

**Comment by undeflabs** [comment] 2018-12-13 14:16
A simple restart fixes the "unknown" problem after using "/admin add MXID", I'm aware of that bug. It happens sometimes for maps that were already added later erase/removed and you add it again. It is still on my to do list.

**Comment by BestNoob** [comment] 2018-12-14 11:01
> 
> 
> A simple restart fixes the "unknown" problem after using "/admin add MXID", I'm aware of that bug. It happens sometimes for maps that were already added later erase/removed and you add it again. It is still on my to do list.

Nope a restart ( i completly restarted all servers and MYSQL) didnt solved the problem for me, only the reset of my databse fixed this, maybe its just 1x entry to remove and reload but i was lazy and resetted it all.

**Comment by undeflabs** [comment] 2018-12-20 13:33
Thanks for the files, I'll take a look into them.

**Comment by ItsPhenom** [comment] 2019-01-14 17:12
Any update on this?

**Comment by undeflabs** [comment] 2019-01-15 13:42
Sorry, not yet

**Comment by BestNoob** [comment] 2019-03-03 10:49
> 
> 
> Sorry, not yet

Is this fixed with actual release ?

**Comment by undeflabs** [comment] 2019-03-03 12:34
I'am not able to reproduce that behavior yet, so I'am still investigating.
Btw.: If it is fixed, this report will be updated and closed. ;)

**Comment by undeflabs** [comment] 2019-06-07 19:02
The "/admin add ID" and "Unknown" result has been fixed with the https://github.com/undeflabs/UASECO/commit/78a3e09022b2ed26ea57be15112811266420dc6a commit.

Your database export works fine in my MariaDB server, no errors shown. So I consider this problem as fixed or not UASECO related. Feel free to reopen if you can add more details.

**Closed by undeflabs** 2019-06-07 19:02 UTC
